export const BaseUrl="http://127.0.0.1:8000";
export const FETCH_CATEGORY_API="FETCH_CATEGORY_API";
export const CREATE_CATEGORY="CREATE_CATEGORY";
export const FETCH_BRAND_API="FETCH_BRAND_API";
export const CREATE_BRAND="CREATE_BRAND";
export const CREATE_SUB_CATEGORY="CREATE_SUB_CATEGORY";
export const GET_ERROR="GET_ERROR";
export const GET_SUB_CATEGORY_WITH_CATEGORY_ID="GET_SUB_CATEGORY_WITH_CATEGORY_ID";
export const CREATE_PRODUCT="CREATE_PRODUCT";
export const GET_ALL_PRODUCTS="GET_ALL_PRODUCTS";
export const GET_PRODUCT_WITH_ID="GET_PRODUCT_WITH_ID";
export const GET_CATEGORY_DATA_WITH_ID="GET_CATEGORY_DATA_WITH_ID";
export const GET_BRAND_API_WITH_ID="GET_BRAND_API_WITH_ID;";
export const GET_LIMIT_PRODUCT_DATA="GET_LIMIT_PRODUCT_DATA";
export const GET_SAME_PRODUCTS="GET_SAME_PRODUCTS";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";
export const GET_PRODUCT_SEARCH="GET_PRODUCT_SEARCH";
export const CREATE_NEW_USER="CREATE_NEW_USER";
export const USER_LOGIN="USER_LOGIN";
export const FORGOT_PASSWORD="FORGOT_PASSWORD";
export const VERIFY_CODE="VERIFY_CODE";
export const REPASSWORD="REPASSWORD";
export const CREATE_RATE="CREATE_RATE";
export const GET_ALL_REVIEWS="GET_ALL_REVIEWS";
export const DELETE_REVIEW="DELETE_REVIEW";
export const UPDATE_COMMENT="UPDATE_COMMENT";
export const ADD_TO_WASH_LIST="ADD_TO_WASH_LIST";
export const DELETE_FROM_WISH_LIST="DELETE_FROM_WISH_LIST";
export const GET_ALL_WISH_LIST="GET_ALL_WISH_LIST";
export const CREATE_COUPON="CREATE_COUPON";
export const GET_ALL_COUPONS="GET_ALL_COUPONS";
export const DELETE_COUPON="DELETE_COUPON";
export const UPDATE_COUPON="UPDATE_COUPON";
export const POST_ADDRESS="POST_ADDRESS";
export const GET_ALL_ADDRESSES="GET_ALL_ADDRESSES";
export const DELETE_ADDRESS="DELETE_ADDRESS";
export const GET_SPACIFIC_ADDRESS="GET_SPACIFIC_ADDRESS";
export const UPDATE_ADDRESS="UPDATE_ADDRESS";
export const UPDATE_USER_PROFILE="UPDATE_USER_PROFILE";
export const UPDATE_USER_PASSWORD="UPDATE_USER_PASSWORD";
export const ADD_TO_CART="ADD_TO_CART";
export const GET_PRODUCTS_CART="GET_PRODUCTS_CART";
export const UPDATE_PRODUCT_QTY="UPDATE_PRODUCT_QTY";
export const USER_USE_COUPON="USER_USE_COUPON";
export const DELETE_ONE_PRODUCT_CART="DELETE_ONE_PRODUCT_CART";
export const DELETE_ALL_CART="DELETE_ALL_CART";


























