export const BaseUrl="http://127.0.0.1:8000";
export const FETCH_CATEGORY_API="FETCH_CATEGORY_API";
export const CREATE_CATEGORY="CREATE_CATEGORY";
export const FETCH_BRAND_API="FETCH_BRAND_API";
export const CREATE_BRAND="CREATE_BRAND";
export const CREATE_SUB_CATEGORY="CREATE_SUB_CATEGORY";
export const GET_ERROR="GET_ERROR";



